language: cpp

sudo: required
dist: trusty

before_install:
    - sudo apt-get -qq update 2>&1 | tee /tmp/apt.log
    - fgrep Failed /tmp/apt.log && sleep 60 && rm /tmp/apt.log && sudo apt-get -qq update 2>&1 | tee /tmp/apt.log || true
    - fgrep Failed /tmp/apt.log && sleep 60 && rm /tmp/apt.log && sudo apt-get -qq update 2>&1 | tee /tmp/apt.log || true
    - travis_retry sudo apt-get install -y fbset v86d
    - travis_retry sudo apt-get install -y "linux-headers-$(uname -r)"

script:
- pushd vfd
- make -C "/usr/src/linux-headers-$(uname -r)" M="$(pwd)"
- sudo insmod vfb.ko
- popd
- sudo dmesg
- sudo fbset -i
- sudo fbset -xres 1920 -yres 1080
- sudo lsmod
- sudo ls -la /dev
- sudo cat /proc/cmdline
- echo done!

