language: python
python:
- '2.7'
- '3.6'
cache: pip
install:
- pip install requests
- pip install beautifulsoup4
script:
- python tests.py
after_success:
- ./push.sh
env:
  global:
    secure: COoCKYWTUf1hgmX2xpc4MU5svxdURqVeovJFqNLOyuw0cBNtxgMdvJSiv1B8DBbIU0oGEycNBM2CVX7rMI660WpeFyBwfAXct05aM6EDAwUpGfknYqOvIOfp2myQF8eAYhXBtAkHHVDcyjWTcy0FkCJeWJtDPhpSyV8oq3u1bkUdrql+w2bxVQfO0OmWuNt7JLE2+wa4OKrS3PIFXnWWdAR5Hb0dVGY3KonoPEpqOaCOvl9sROHRlyO6jhu2k+Gw9g9rWqtGXVwgMPdpHzuXN6BTdIBEQ2zzGYz+EIxnuvXmTNDsKkmHTik++OreihjnDCU9HzPk6YLnZsXK6ttBwT3ydzT5uhoQ1IbtfoUALYRZe3seTA5yxqf4CYuP7IN3qGo3eusz2tmdYsAbdS2toLNC60UOWu6oIST8Rym7iRuBbeCJJvhrAoqXTTa/TSGZLySDJ/O53uPGMiss7dtJsF/hvM/q6aGI+Pk6m6XAVRile6gHotE+wZDGO8MF4FdxfEgs3UstXe3LPhyS7V3Dg1zrOVhVkt/L8H58VnfLCFzIH9qODlDhBs0ULnbducM+VG3q9UfKUujCwqN5ymHLzZWYkDLdFT18eukD2ueaYXCBrs3LQuMRuRoWp2mQDba1+z/okfFV3RUtALIDBYY+mAI8faRb1GKw6JPSvEsh088=
